name: "Build Java Project"
description: "Compiles and tests a Java project using Maven"
author: "Abhilash"

inputs:
  java-version:
    description: "Java version to use"
    required: false
    default: "17"

runs:
  using: "composite"
  steps:
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: ${{ inputs.java-version }}

    - name: Build project
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test
